name: project
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  freezed_annotation:
  percent_indicator:
  flutter_riverpod:
  go_router:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  freezed:
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
